### ISSUE TITLE
Lack of Complete test coverage and Unittests

### ISSUE THREAD

**Issue by pradyunsg** [musiKk/plyj#11]
> 

As I refactored model.py for #10, to me it became obvious that there is a lack of unittests for the same.

As I looked into the code, I realized a lot of it is never tested (BAD)!

Here are the stats from coverage.py:
```
Name          Stmts   Miss  Cover
---------------------------------
plyj\model      680    317    53%
plyj\parser     917    332    64%
---------------------------------
TOTAL          1597    649    59%
```

Obviously this is not good. In fact when you look at it more closely, you see that a good part of the 59% is the declarations of methods, classes etc.
That means that most of the "code" is un-executed during testing, from which we infer that if the implementation changes and breaks in future, the tests won't reveal it. This definitely has to be fixed.

--------------
Few things about testing:  Read [this][2] and [this][3]. Try [this][4] tutorial too.

 [1]: http://pythoscope.com
 [2]: http://stackoverflow.com/a/67500/1931274
 [3]: http://sd.jtimothyking.com/2006/07/11/twelve-benefits-of-writing-unit-tests-first/
 [4]: http://www.openp2p.com/pub/a/python/2004/12/02/tdd_pyunit.html

**Comment by musiKk** [comment]
Closing this now. Adding tests is an ongoing process and not something with a defined goal. I'm certainly not shooting for 100% coverage on principle. And even that may not be enough.
