### ISSUE TITLE
visit_MethodInvocation(self, met_invocation)

### ISSUE THREAD

**Issue by chunrong** [musiKk/plyj#34]
I visited methodInvocation. But some method invocations are missed. 

For example:
Missed:
public static final String LOG_TAG = ACRA.class.getSimpleName();
ErrorReporter localErrorReporter = ErrorReporter.getInstance();
Visited:
MethodInvocation(name='getApplicationContext', arguments=[], type_arguments=[], target=Name(value='paramReportsCrashes'))
MethodInvocation(name='d', arguments=[Name(value='LOG_TAG'), Additive(operator='+', lhs=Additive(operator='+', lhs=Literal(value='"ACRA is enabled for "'), rhs=MethodInvocation(name='getPackageName', arguments=[], type_arguments=[], target=Name(value='paramReportsCrashes'))), rhs=Literal(value='", intializing..."'))], type_arguments=[], target=Name(value='Log'))
MethodInvocation(name='init', arguments=[Name(value='paramReportsCrashes'), Name(value='paramBoolean')], type_arguments=[], target=Name(value='localErrorReporter'))
MethodInvocation(name='setDefaultUncaughtExceptionHandler', arguments=[Name(value='localErrorReporter')], type_arguments=[], target=Name(value='Thread'))
MethodInvocation(name='setReportSender', arguments=[InstanceCreation(type=Type(name=Name(value='HttpPostSender'), type_arguments=[], enclosed_in=None, dimensions=0), type_arguments=[], arguments=[Name(value='paramString')], body=[], enclosed_in=None)], type_arguments=[], target=Name(value='localErrorReporter'))
MethodInvocation(name='checkReportsOnApplicationStart', arguments=[], type_arguments=[], target=Name(value='localErrorReporter'))
package com.facebook.acra;

import android.content.Context;
import android.util.Log;
import com.facebook.acra.reporter.ReportsCrashes;
import com.facebook.acra.sender.HttpPostSender;

public class ACRA
{
  public static final ReportField[] ALL_CRASH_REPORT_FIELDS = {ReportField.ATTACHMENT_ORIGINAL_SIZE };
public static final String LOG_TAG = ACRA.class.getSimpleName();
  public static final String NULL_VALUE = "ACRA-NULL-STRING";
  private static ReportsCrashes mReportsCrashes;
  
  public ACRA() {}
  
  public static ReportsCrashes getConfig()
  {
    return mReportsCrashes;
  }
  
  public static ErrorReporter init(ReportsCrashes paramReportsCrashes, String paramString, boolean paramBoolean)
  {
    ErrorReporter localErrorReporter = ErrorReporter.getInstance();
    if (mReportsCrashes == null)
    {
      mReportsCrashes = paramReportsCrashes;
      paramReportsCrashes = paramReportsCrashes.getApplicationContext();
      Log.d(LOG_TAG, "ACRA is enabled for " + paramReportsCrashes.getPackageName() + ", intializing...");
      localErrorReporter.init(paramReportsCrashes, paramBoolean);
      Thread.setDefaultUncaughtExceptionHandler(localErrorReporter);
      if (paramString != null) {
        localErrorReporter.setReportSender(new HttpPostSender(paramString));
      }
      localErrorReporter.checkReportsOnApplicationStart();
    }
    return localErrorReporter;
  }
}

Thanks for your help.

**Comment by chunrong** [comment]
The reason might be that "VariableDeclarator" doesn't implement accept().
Thanks,

**Comment by musiKk** [comment]
This is weird. Could you provide your parsing code? I copy and pasted your Java code and parsed it as follows:

```
import plyj.parser as plyj
parser = plyj.Parser()

tree = parser.parse_string('''
your code here
''')

import plyj.model as m
class V(m.Visitor):
    def visit_MethodInvocation(self, mi):
        print ' - {}'.format(mi.name)

tree.accept(V())
```

This prints

```
 - getSimpleName
 - getInstance
 - getApplicationContext
 - d
 - init
 - setDefaultUncaughtExceptionHandler
 - setReportSender
 - checkReportsOnApplicationStart
```

which includes the two you're missing.

Incidentally you discovered another bug: My version is missing the `getPackageName` from the string concatenation. :)

**Comment by chunrong** [comment]
Thanks for your quick reply!
I just added visit_MethodInvocation plyj/example/symbols_visitor.py.
I tried again and found a conflict between field and mi. If they existed together, some mi would be missing.

class V(m.Visitor):
    def visit_FieldDeclaration(self, fd):
        print 'Field - {}'.format(fd.type.name.value)
    def visit_MethodInvocation(self, mi):
        print 'Mi - {}'.format(mi.name)

**Comment by musiKk** [comment]
Yes, in this case, it would miss `getSimpleName`. The current design of the accept methods requires a return value of `True` from all visitor methods if the children should be recursively visited. If you have a field declaration that has a method invocation as a variable initializer that should be visited, your `visit_FieldDeclaration` has to `return True`, otherwise the rest is skipped.

This does not fix the missing `getPackageName` which, I think, is caused by some inheritance mumbo jumbo...

**Comment by chunrong** [comment]
Thank you very much. And look forward to your update.

**Comment by musiKk** [comment]
Uhm. So I feel a bit stupid now. This was no bug. Of course `getSimpleType` is omitted. It's part of the argument list of a method invocation itself and since our `visit_MethodInvocation` does not return `True` the visitor does not recurse into it. If you return `True`, everything is visited as it should.

Feel free to reopen if you still have an issue.
