### ISSUE TITLE
Unparsing?

### ISSUE THREAD

**Issue by amitmaor** [musiKk/plyj#36]
Hi there, 

I'm using your parser for a project that I'm working on. Within that project, I have to parse large amounts Java code in order to find specific functions with certain characteristics (i.e. contain certain loops or recursive calls). Once I find those functions, I need to save them elsewhere and run them separately. To do this, though, I need to unparse the code from its parsed form so that it can be run as normal java code.

Do you have suggestions as to how I could take the parsed version of your code and unparse it back into java? Alternatively, is it possible to only partially parse, say, a ClassDeclaration, such that the "body" field is still in Java?

I recognize this may not be possible -- just trying to save myself a lot of work...

Thanks so much for making this! It's been super helpful so far.

**Comment by musiKk** [comment]
I'm really glad you like it.

To the best of my knowledge it is not possible to leave certain portions unparsed.

Unparsing per se should be relatively straightforward. You could whip up a visitor, implement the methods you need and have them print out what they visited. I guess this becomes rather tedious and visitors aren't really battle tested yet (cf. #34). The foolproof way would be to take the parsed structure and print everything by hand. This surely is at least as tedious but much better tested and should work fine.

I guess once it works such a visitor could easily become part of the plyj examples ore even part of the library itself.
