### ISSUE TITLE
Inability to create Tree

### ISSUE THREAD

**Issue by SecBro1** [musiKk/plyj#37]
We are attempting to parse Android source code and frequently encounter an error where the "tree" type is None.  Below is the code and one of the many files which apparently can't be parsed, while numerous others have no problems. Any ideas?

The code in our project, in this case, couldn't be simpler:

j is a list element from a loop over all the Java files, ie: for j in java_files, same as all the working ones

comp_type is a string

########################

import lib.plyj.parser as plyj

tree=''

parser = plyj.Parser()

def tree_parser(j,comp_type):
        global tree
        global parser

        try:

                tree=parser.parse_file(j) #This returns type(tree)==None on the file below, but works on numerous others

Any assistance you're willing to offer is appreciated.

#########################

package com.and;

import android.app.Activity;
import android.app.Dialog;
import android.content.Intent;
import android.os.Bundle;
import android.text.Editable;
import android.view.View;
import android.view.View.OnClickListener;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.TextView;
import com.and.response.Loginresponse;
import com.and.service.Loginservice;
import com.and.util.FileUtil;
import com.and.util.Globals;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.io.PrintStream;

public class MainActivity extends Activity
{
  private CheckBox Fiddlercheckbox;
  private CheckBox checkbox;
  private EditText ip;
  private Loginresponse loginresponse;
  private Loginservice loginservice;
  private Dialog myDialog;
  private EditText password;
  private ImageView settingImage;
  private EditText username;

  public void onCreate(Bundle paramBundle)
  {
    super.onCreate(paramBundle);
    this.loginservice = new Loginservice();
    if (!FileUtil.filesexistscheck("/data/data/com.and/files/Disclaimer.xml"))
    {
      this.myDialog = new Dialog(this);
      this.myDialog.setContentView(2130903042);
      this.myDialog.setTitle("Disclaimer");
      ((Button)this.myDialog.findViewById(2131034121)).setOnClickListener(new View.OnClickListener()
      {
        public void onClick(View paramView)
        {
          MainActivity.this.myDialog.dismiss();
          try
          {
            OutputStreamWriter localOutputStreamWriter = new OutputStreamWriter(MainActivity.this.openFileOutput("Disclaimer.xml", 1));
            localOutputStreamWriter.write("<Done>Yes</Done>");
            localOutputStreamWriter.flush();
            localOutputStreamWriter.close();
            return;
          }
          catch (IOException localIOException)
          {
            localIOException.printStackTrace();
          }
        }
      });
    }
    if ((FileUtil.filesexistscheck("/data/data/com.and/files/creds.xml")) && (!Globals.ServerIP.equals("")))
    {
      Intent localIntent = new Intent(this, loginactivity2.class);
      localIntent.putExtra("check", "exists");
      startActivity(localIntent);
      finish();
    }
    setContentView(2130903045);
    ((Button)findViewById(2131034121)).setOnClickListener(new View.OnClickListener()
    {
      public void onClick(View paramView)
      {
        MainActivity.this.username = ((EditText)MainActivity.this.findViewById(2131034132));
        MainActivity.this.password = ((EditText)MainActivity.this.findViewById(2131034117));
        MainActivity.this.checkbox = ((CheckBox)MainActivity.this.findViewById(2131034134));
        MainActivity.this.ip = ((EditText)MainActivity.this.findViewById(2131034133));
        Globals.ServerIP = MainActivity.this.ip.getText().toString();
        if ((Globals.ServerIP.equals("127.0.0.1")) || (Globals.ServerIP.equals("localhost")) || (Globals.ServerIP.equals("")))
        {
          System.out.print("ERROR: Invalid Server IP!");
          MainActivity.this.myDialog = new Dialog(MainActivity.this);
          MainActivity.this.myDialog.setContentView(2130903047);
          MainActivity.this.myDialog.setTitle("Invalid Server IP!");
          ((TextView)MainActivity.this.myDialog.findViewById(2131034143)).setText("Remember to use the system's real IP rather than 127.0.0.1 or localhost.\n\n");
          MainActivity.this.myDialog.setCancelable(true);
          ((Button)MainActivity.this.myDialog.findViewById(2131034113)).setOnClickListener(new View.OnClickListener()
          {
            public void onClick(View paramView)
            {
              MainActivity.this.myDialog.dismiss();
              Intent localIntent = new Intent(MainActivity.this, MainActivity.class);
              MainActivity.this.startActivity(localIntent);
              MainActivity.this.finish();
            }
          });
          MainActivity.this.myDialog.show();
          return;
        }
        TextView localTextView;
        if (MainActivity.this.checkbox.isChecked())
        {
          Globals.Httpsflag = Boolean.valueOf(true);
          Globals.PostURL = "https://" + Globals.ServerIP + ":" + Globals.ServerPort + "/spring-ws-standalone/ws";
          MainActivity.this.loginresponse = MainActivity.this.loginservice.send(MainActivity.this.username.getText().toString(), MainActivity.this.password.getText().toString());
          if ((MainActivity.this.loginresponse != null) && (!MainActivity.this.loginresponse.getSessionid().equals("failed")))
            break label573;
          MainActivity.this.myDialog = new Dialog(MainActivity.this);
          MainActivity.this.myDialog.setContentView(2130903047);
          MainActivity.this.myDialog.setTitle("Login Failed!");
          localTextView = (TextView)MainActivity.this.myDialog.findViewById(2131034143);
          if ((MainActivity.this.loginresponse != null) || (!Globals.Httpsflag.booleanValue()))
            break label518;
          localTextView.setText("Could not connect to the server.\n\nCheck the user guide for Lessons 9 and 10. You'll have to hack some stuff first!");
        }
        while (true)
        {
          MainActivity.this.myDialog.setCancelable(true);
          ((Button)MainActivity.this.myDialog.findViewById(2131034113)).setOnClickListener(new View.OnClickListener()
          {
            public void onClick(View paramView)
            {
              MainActivity.this.myDialog.dismiss();
              Intent localIntent = new Intent(MainActivity.this, MainActivity.class);
              MainActivity.this.startActivity(localIntent);
              MainActivity.this.finish();
            }
          });
          MainActivity.this.myDialog.show();
          return;
          Globals.Httpsflag = Boolean.valueOf(false);
          break;
          label518: if (MainActivity.this.loginresponse == null)
          {
            localTextView.setText("Could not connect to the server.\n\n");
            continue;
          }
          if (MainActivity.this.loginresponse.getSessionid().equals("failed"))
          {
            localTextView.setText("Please check the username and password then try again.\n\n");
            continue;
          }
          localTextView.setText("Wierd Uknown Error!!! OH NOEZ!");
        }
        label573: Intent localIntent = new Intent(MainActivity.this, loginactivity2.class);
        Globals.initialize(MainActivity.this.username.getText().toString(), MainActivity.this.loginresponse.getSessionid(), MainActivity.this.loginresponse.getAccountnumber());
        localIntent.putExtra("Username", MainActivity.this.username.getText().toString());
        localIntent.putExtra("check", "doesnot");
        localIntent.putExtra("Password", MainActivity.this.password.getText().toString());
        MainActivity.this.startActivity(localIntent);
        MainActivity.this.finish();
      }
    });
    this.settingImage = ((ImageView)findViewById(2131034135));
    this.settingImage.setOnClickListener(new View.OnClickListener()
    {
      public void onClick(View paramView)
      {
        Intent localIntent = new Intent(MainActivity.this, Proxysetting.class);
        MainActivity.this.startActivity(localIntent);
        MainActivity.this.finish();
      }
    });
  }
}

**Comment by musiKk** [comment]
It looks like this issue will have the same fate as #35. I haven't looked into the grammar yet but both Eclipse and javac reject a variable declaration with a label. This appears in your code and it is the cause for the problem:

    label573: Intent localIntent = new Intent(MainActivity.this, loginactivity2.class);

The thing is, I'd really like to make it work for you but in all likelihood the changes to the grammar required for this will be substantial.

If you are the creator of the source code, you can move the label to the next line in order to make it work again. In case it's foreign code, well, I'll have a look but don't get your hopes too high.

Sorry.

**Comment by musiKk** [comment]
So it's been a while but I just looked into the grammar and yeah, a *BlockStatement* is either a *LocalVariableDeclarationStatement*, a *ClassOrInterfaceDeclaration* or *[Identifier :] Statement*. So you cannot have a label in front of a variable declaration.

Again, very sorry but open to pull requests.
