### ISSUE TITLE
Information loss of FieldDeclaration Types Dimension

### ISSUE THREAD

**Issue by AKST** [musiKk/plyj#39]
Here is a sample file

```java
/* IndexUF.java */
public class IndexUF<T extends Object> {
  private Indexed<T>[] parent;

  static private class Indexed<T> {
    public int index;
    public T value;
  }
}
```

When I check the parse output of `parent`'s type's dimension, it is set too `0` so example below will fail the assertion.

```python
index_uf = parser.parse_file(file('IndexUF.java'))
assert index_uf.type_declarations[0].body[0].type.dimensions == 1
```

I found this while testing the output of my pretty printer, and it turned out the issue was in the AST.

**Comment by musiKk** [comment]
Thanks! Fixed in master.

**Comment by AKST** [comment]
No worries!
