### ISSUE TITLE
Unable to understand in which format is the tree generated

### ISSUE THREAD

**Issue by divyabiyani** [musiKk/plyj#45]
Could you please tell me in which format is your output generated?
Because when i a storing it in a .txt file,I am getting a line containing all the information.

Whereas what i want is something of this format:

CompilationUnit
 TypeDeclaration
  ClassDeclaration:(package private)
   UnmodifiedClassDeclaration(Example)
    ClassBody
     ClassBodyDeclaration
      MethodDeclaration:(package private)
       ResultType
       MethodDeclarator(bar)
        FormalParameters
       Block
        BlockStatement
         Statement
          WhileStatement
           Expression
            PrimaryExpression
             PrimaryPrefix
              Name:baz
           Statement
            StatementExpression:null
             PrimaryExpression
              PrimaryPrefix
               Name:buz.doSomething
              PrimarySuffix
               Arguments

Is it somehow possible?

**Comment by A-AFTAHI** [comment]
same here. i think we have to do this ourselves

**Comment by musiKk** [comment]
Wow, this is a very old question. I'm not quite sure I get it though. The [model](https://github.com/musiKk/plyj/blob/master/plyj/model.py) contains `__repr__` methods for convenience but of course the whole thing is just a data structure and if you want something, you have to do it yourself. A simple list of all symbols can be achieved relatively easily with the visitor API.

I'm closing this now. If you have problems, feel free to open another issue!
