### ISSUE TITLE
extracting method's code from java files

### ISSUE THREAD

**Issue by nxs5899** [musiKk/plyj#49]
Hi.
I want to find out each method in a java file, then get the method's code.

I appreciate if you can help me with this.

**Comment by musiKk** [comment]
Would [this example](https://github.com/musiKk/plyj/blob/master/example/symbols_visitor.py) already help you? Look for the `visit_MethodDeclaration` method. Alternatively you can use the "manual" version that is not based on the visitor pattern which is in `symbols.py` in the same directory.

**Comment by nxs5899** [comment]
Hi Werner.

thank you for your feedback on my question. and sorry for replying this
late, since I have been traveling.
I had already looked at the example you mentioned and this was helpful for
printing the method names. however, in my case, I need to print the whole
body of every method in the java file one by one.
your feedback is highly appreciated.

Nasir

**Comment by musiKk** [comment]
Printing the body would require some sort of serialization mechanism which does not exist in plyj.

If ply provides easy access to spans of parsed text, it might be possible get offsets in the original code and use that (essentially slices of the original java file) but I don't remember if this is present and even if I think it would need support from plyj as well.

Long story short, not possible in the current state of the library, sorry.
