### ISSUE TITLE
Line Number and Position Tracking

### ISSUE THREAD

**Issue by 1070148808** [musiKk/plyj#51]
Excuse me, I want to track the line number of the code in the grammar analysis（yacc）, but modifying your code according to the official document can not find the current number information in the result. What should I do?

Thank you very much for your help！！！！！！

```
def p_expression(p):
     'expression : expression PLUS expression'
     p.lineno(1)        # Line number of the left expression
     p.lineno(2)        # line number of the PLUS operator
     p.lineno(3)        # line number of the right expression
     ...
     start,end = p.linespan(3)    # Start,end lines of the right expression
     starti,endi = p.lexspan(3)   # Start,end positions of right expression
```

**Comment by 1070148808** [comment]
I want to know the line numbers of all methods, but I don't know how to modify your code.

**Comment by musiKk** [comment]
I am not sure. Did you enable tracking of line numbers as explained [here](http://www.dabeaz.com/ply/ply.html#ply_nn9)? I'm not sure if that's necessary but could be worth a shot.

**Comment by 1070148808** [comment]
> I am not sure. Did you enable tracking of line numbers as explained [here](http://www.dabeaz.com/ply/ply.html#ply_nn9)? I'm not sure if that's necessary but could be worth a shot.

thans for u help,the problem shas been resolved
